package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.TeamBean;
import greendao.PlayerBean;
import greendao.TeamPlayer;

import greendao.TeamBeanDao;
import greendao.PlayerBeanDao;
import greendao.TeamPlayerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teamBeanDaoConfig;
    private final DaoConfig playerBeanDaoConfig;
    private final DaoConfig teamPlayerDaoConfig;

    private final TeamBeanDao teamBeanDao;
    private final PlayerBeanDao playerBeanDao;
    private final TeamPlayerDao teamPlayerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teamBeanDaoConfig = daoConfigMap.get(TeamBeanDao.class).clone();
        teamBeanDaoConfig.initIdentityScope(type);

        playerBeanDaoConfig = daoConfigMap.get(PlayerBeanDao.class).clone();
        playerBeanDaoConfig.initIdentityScope(type);

        teamPlayerDaoConfig = daoConfigMap.get(TeamPlayerDao.class).clone();
        teamPlayerDaoConfig.initIdentityScope(type);

        teamBeanDao = new TeamBeanDao(teamBeanDaoConfig, this);
        playerBeanDao = new PlayerBeanDao(playerBeanDaoConfig, this);
        teamPlayerDao = new TeamPlayerDao(teamPlayerDaoConfig, this);

        registerDao(TeamBean.class, teamBeanDao);
        registerDao(PlayerBean.class, playerBeanDao);
        registerDao(TeamPlayer.class, teamPlayerDao);
    }
    
    public void clear() {
        teamBeanDaoConfig.getIdentityScope().clear();
        playerBeanDaoConfig.getIdentityScope().clear();
        teamPlayerDaoConfig.getIdentityScope().clear();
    }

    public TeamBeanDao getTeamBeanDao() {
        return teamBeanDao;
    }

    public PlayerBeanDao getPlayerBeanDao() {
        return playerBeanDao;
    }

    public TeamPlayerDao getTeamPlayerDao() {
        return teamPlayerDao;
    }

}
