package greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import greendao.MatchBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MATCH_BEAN.
*/
public class MatchBeanDao extends AbstractDao<MatchBean, Long> {

    public static final String TABLENAME = "MATCH_BEAN";

    /**
     * Properties of entity MatchBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Start = new Property(2, java.util.Date.class, "start", false, "START");
        public final static Property End = new Property(3, java.util.Date.class, "end", false, "END");
        public final static Property CurrentPoint = new Property(4, int.class, "currentPoint", false, "CURRENT_POINT");
        public final static Property TeamId = new Property(5, long.class, "teamId", false, "TEAM_ID");
    };

    private DaoSession daoSession;

    private Query<MatchBean> teamBean_MatchBeanListQuery;

    public MatchBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MatchBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MATCH_BEAN' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'START' INTEGER," + // 2: start
                "'END' INTEGER," + // 3: end
                "'CURRENT_POINT' INTEGER NOT NULL ," + // 4: currentPoint
                "'TEAM_ID' INTEGER NOT NULL );"); // 5: teamId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MATCH_BEAN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MatchBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
 
        java.util.Date start = entity.getStart();
        if (start != null) {
            stmt.bindLong(3, start.getTime());
        }
 
        java.util.Date end = entity.getEnd();
        if (end != null) {
            stmt.bindLong(4, end.getTime());
        }
        stmt.bindLong(5, entity.getCurrentPoint());
        stmt.bindLong(6, entity.getTeamId());
    }

    @Override
    protected void attachEntity(MatchBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MatchBean readEntity(Cursor cursor, int offset) {
        MatchBean entity = new MatchBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // start
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // end
            cursor.getInt(offset + 4), // currentPoint
            cursor.getLong(offset + 5) // teamId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MatchBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setStart(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setEnd(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setCurrentPoint(cursor.getInt(offset + 4));
        entity.setTeamId(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MatchBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MatchBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "matchBeanList" to-many relationship of TeamBean. */
    public List<MatchBean> _queryTeamBean_MatchBeanList(long teamId) {
        synchronized (this) {
            if (teamBean_MatchBeanListQuery == null) {
                QueryBuilder<MatchBean> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TeamId.eq(null));
                teamBean_MatchBeanListQuery = queryBuilder.build();
            }
        }
        Query<MatchBean> query = teamBean_MatchBeanListQuery.forCurrentThread();
        query.setParameter(0, teamId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTeamBeanDao().getAllColumns());
            builder.append(" FROM MATCH_BEAN T");
            builder.append(" LEFT JOIN TEAM_BEAN T0 ON T.'TEAM_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MatchBean loadCurrentDeep(Cursor cursor, boolean lock) {
        MatchBean entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TeamBean teamBean = loadCurrentOther(daoSession.getTeamBeanDao(), cursor, offset);
         if(teamBean != null) {
            entity.setTeamBean(teamBean);
        }

        return entity;    
    }

    public MatchBean loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MatchBean> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MatchBean> list = new ArrayList<MatchBean>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MatchBean> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MatchBean> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
