package greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import greendao.PlayerPoint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLAYER_POINT.
*/
public class PlayerPointDao extends AbstractDao<PlayerPoint, Long> {

    public static final String TABLENAME = "PLAYER_POINT";

    /**
     * Properties of entity PlayerPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Role = new Property(1, String.class, "role", false, "ROLE");
        public final static Property PlayerId = new Property(2, long.class, "playerId", false, "PLAYER_ID");
        public final static Property PointId = new Property(3, long.class, "pointId", false, "POINT_ID");
    };

    private DaoSession daoSession;

    private Query<PlayerPoint> pointBean_PlayerPointListQuery;

    public PlayerPointDao(DaoConfig config) {
        super(config);
    }
    
    public PlayerPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLAYER_POINT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROLE' TEXT NOT NULL ," + // 1: role
                "'PLAYER_ID' INTEGER NOT NULL ," + // 2: playerId
                "'POINT_ID' INTEGER NOT NULL );"); // 3: pointId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLAYER_POINT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PlayerPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRole());
        stmt.bindLong(3, entity.getPlayerId());
        stmt.bindLong(4, entity.getPointId());
    }

    @Override
    protected void attachEntity(PlayerPoint entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PlayerPoint readEntity(Cursor cursor, int offset) {
        PlayerPoint entity = new PlayerPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // role
            cursor.getLong(offset + 2), // playerId
            cursor.getLong(offset + 3) // pointId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PlayerPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRole(cursor.getString(offset + 1));
        entity.setPlayerId(cursor.getLong(offset + 2));
        entity.setPointId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PlayerPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PlayerPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "playerPointList" to-many relationship of PointBean. */
    public List<PlayerPoint> _queryPointBean_PlayerPointList(long pointId) {
        synchronized (this) {
            if (pointBean_PlayerPointListQuery == null) {
                QueryBuilder<PlayerPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PointId.eq(null));
                pointBean_PlayerPointListQuery = queryBuilder.build();
            }
        }
        Query<PlayerPoint> query = pointBean_PlayerPointListQuery.forCurrentThread();
        query.setParameter(0, pointId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPlayerBeanDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPointBeanDao().getAllColumns());
            builder.append(" FROM PLAYER_POINT T");
            builder.append(" LEFT JOIN PLAYER_BEAN T0 ON T.'PLAYER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN POINT_BEAN T1 ON T.'POINT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PlayerPoint loadCurrentDeep(Cursor cursor, boolean lock) {
        PlayerPoint entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PlayerBean playerBean = loadCurrentOther(daoSession.getPlayerBeanDao(), cursor, offset);
         if(playerBean != null) {
            entity.setPlayerBean(playerBean);
        }
        offset += daoSession.getPlayerBeanDao().getAllColumns().length;

        PointBean pointBean = loadCurrentOther(daoSession.getPointBeanDao(), cursor, offset);
         if(pointBean != null) {
            entity.setPointBean(pointBean);
        }

        return entity;    
    }

    public PlayerPoint loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PlayerPoint> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PlayerPoint> list = new ArrayList<PlayerPoint>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PlayerPoint> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PlayerPoint> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
