package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEAM_BEAN.
 */
public class TeamBean implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private java.util.Date creation;

    public TeamBean() {
    }

    public TeamBean(Long id) {
        this.id = id;
    }

    public TeamBean(Long id, String name, java.util.Date creation) {
        this.id = id;
        this.name = name;
        this.creation = creation;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public java.util.Date getCreation() {
        return creation;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreation(java.util.Date creation) {
        this.creation = creation;
    }

}
